import type { Appointment, Status } from "../types/appointments.types";

export const APPOINTMENTS_INITIAL: Appointment[] = [
  {
    id: "APT-001",
    time: "08:30",
    customer: "Nguyễn Thị Mai",
    pet: "Mochi",
    species: "Chó",
    service: "Khám tổng quát",
    staff: "BS. Trần Hoài Nam",
    status: "completed",
    amount: "250.000",
    phone: "090 1234 5678",
    email: "mai@email.com",
    notes: "Kiểm tra sức khoẻ định kỳ hàng năm",
  },
  {
    id: "APT-002",
    time: "09:00",
    customer: "Phạm Văn Đức",
    pet: "Kiwi",
    species: "Mèo",
    service: "Tiêm phòng dại",
    staff: "BS. Lê Thị Hoa",
    status: "completed",
    amount: "180.000",
    phone: "090 2345 6789",
    email: "duc@email.com",
  },
  {
    id: "APT-003",
    time: "09:30",
    customer: "Lê Thị Hương",
    pet: "Buddy",
    species: "Chó",
    service: "Grooming cao cấp",
    staff: "NV. Vũ Minh Tuấn",
    status: "in_progress",
    amount: "350.000",
    phone: "090 3456 7890",
    notes: "Yêu cầu cắt theo kiểu teddy bear",
  },
  {
    id: "APT-004",
    time: "10:00",
    customer: "Trần Minh Khoa",
    pet: "Luna",
    species: "Mèo",
    service: "Khám da liễu",
    staff: "BS. Trần Hoài Nam",
    status: "in_progress",
    amount: "320.000",
    phone: "090 4567 8901",
    email: "khoa@email.com",
    notes: "Dị ứng Penicillin — cần đặc biệt chú ý",
  },
  {
    id: "APT-005",
    time: "10:30",
    customer: "Hoàng Thanh Thảo",
    pet: "Max",
    species: "Chó",
    service: "Lưu trú 3 ngày",
    staff: "NV. Đinh Thị Lan",
    status: "scheduled",
    amount: "900.000",
    phone: "090 5678 9012",
  },
  {
    id: "APT-006",
    time: "11:00",
    customer: "Võ Thị Bích",
    pet: "Coco",
    species: "Chó",
    service: "Khám tổng quát",
    staff: "BS. Lê Thị Hoa",
    status: "scheduled",
    amount: "250.000",
    phone: "090 6789 0123",
  },
  {
    id: "APT-007",
    time: "11:30",
    customer: "Đặng Quốc Hùng",
    pet: "Snowball",
    species: "Mèo",
    service: "Tiêm phòng combo",
    staff: "BS. Trần Hoài Nam",
    status: "scheduled",
    amount: "380.000",
    phone: "090 7890 1234",
  },
  {
    id: "APT-008",
    time: "14:00",
    customer: "Bùi Thị Lan",
    pet: "Charlie",
    species: "Chó",
    service: "Phẫu thuật triệt sản",
    staff: "BS. Nguyễn Đức Trung",
    status: "scheduled",
    amount: "1.500.000",
    phone: "090 8901 2345",
    notes: "Cần nhịn ăn trước 8 tiếng",
  },
  {
    id: "APT-009",
    time: "14:30",
    customer: "Ngô Văn Tâm",
    pet: "Whiskers",
    species: "Mèo",
    service: "Grooming tiêu chuẩn",
    staff: "NV. Vũ Minh Tuấn",
    status: "cancelled",
    amount: "280.000",
    phone: "090 9012 3456",
  },
  {
    id: "APT-010",
    time: "15:00",
    customer: "Dương Thị Thu",
    pet: "Rocky",
    species: "Chó",
    service: "Khám ngoại khoa",
    staff: "BS. Nguyễn Đức Trung",
    status: "scheduled",
    amount: "380.000",
    phone: "090 0123 4567",
  },
  {
    id: "APT-011",
    time: "15:30",
    customer: "Phan Anh Tuấn",
    pet: "Milo",
    species: "Chó",
    service: "Tắm và vệ sinh tai",
    staff: "NV. Vũ Minh Tuấn",
    status: "scheduled",
    amount: "150.000",
    phone: "091 1234 5678",
  },
  {
    id: "APT-012",
    time: "16:00",
    customer: "Trịnh Thị Nga",
    pet: "Nala",
    species: "Mèo",
    service: "Kiểm tra định kỳ",
    staff: "BS. Lê Thị Hoa",
    status: "scheduled",
    amount: "200.000",
    phone: "091 2345 6789",
  },
];

export const APPOINTMENT_STATUS_CFG: Record<
  Status,
  { label: string; cls: string; dot: string }
> = {
  scheduled: {
    label: "Chờ khám",
    cls: "bg-blue-50 text-blue-700 ring-1 ring-inset ring-blue-200",
    dot: "bg-blue-500",
  },
  in_progress: {
    label: "Đang khám",
    cls: "bg-amber-50 text-amber-700 ring-1 ring-inset ring-amber-200",
    dot: "bg-amber-500",
  },
  completed: {
    label: "Hoàn thành",
    cls: "bg-emerald-50 text-emerald-700 ring-1 ring-inset ring-emerald-200",
    dot: "bg-emerald-500",
  },
  cancelled: {
    label: "Đã huỷ",
    cls: "bg-red-50 text-red-600 ring-1 ring-inset ring-red-200",
    dot: "bg-red-400",
  },
};

export const APPOINTMENT_SERVICES = [
  "Khám tổng quát",
  "Khám da liễu",
  "Khám ngoại khoa",
  "Khám nội khoa chuyên sâu",
  "Tiêm phòng dại",
  "Combo 5 bệnh (chó)",
  "Combo 4 bệnh (mèo)",
  "Grooming đầy đủ",
  "Tắm & sấy tiêu chuẩn",
  "Lưu trú tiêu chuẩn",
  "Phẫu thuật triệt sản",
  "Siêu âm bụng",
];

export const APPOINTMENT_DOCTORS = [
  "BS. Trần Hoài Nam",
  "BS. Lê Thị Hoa",
  "BS. Nguyễn Đức Trung",
  "NV. Vũ Minh Tuấn",
  "NV. Đinh Thị Lan",
];
