import type { ElementType } from "react";
import {
  BedDouble,
  Briefcase,
  Scissors,
  Stethoscope,
  Users,
} from "lucide-react";
import type {
  Department,
  Shift,
  StaffMember,
  WorkStatus,
} from "../types/staff.types";

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: "NV-C01",
    name: "BS. Trần Hoài Nam",
    avatar: "TN",
    department: "clinic",
    position: "Bác sĩ trưởng",
    phone: "0901 111 222",
    email: "nam.tran@petcare.vn",
    joinDate: "15/03/2020",
    shift: "Cả ngày (7–19h)",
    workStatus: "active",
    locked: false,
    todayTasks: 6,
    completedTasks: 4,
    monthlyPerf: 96,
    rating: 4.9,
    specialty: "Nội khoa",
    room: "Phòng 1",
    licenseNo: "VN-VET-2018-0412",
    todayPatients: 4,
    notes: "Bác sĩ trưởng khoa nội. Chuyên gia về bệnh da liễu mèo.",
  },
  {
    id: "NV-C02",
    name: "BS. Lê Thị Hoa",
    avatar: "LH",
    department: "clinic",
    position: "Bác sĩ thú y",
    phone: "0902 222 333",
    email: "hoa.le@petcare.vn",
    joinDate: "02/07/2021",
    shift: "Cả ngày (7–19h)",
    workStatus: "active",
    locked: false,
    todayTasks: 5,
    completedTasks: 3,
    monthlyPerf: 91,
    rating: 4.8,
    specialty: "Thú y đa khoa",
    room: "Phòng 2",
    licenseNo: "VN-VET-2019-0891",
    todayPatients: 3,
    notes: "Giỏi tiếp xúc thú cưng nhỏ và thú cưng lo lắng.",
  },
  {
    id: "NV-C03",
    name: "BS. Nguyễn Đức Trung",
    avatar: "NT",
    department: "clinic",
    position: "Bác sĩ phẫu thuật",
    phone: "0903 333 444",
    email: "trung.nguyen@petcare.vn",
    joinDate: "18/11/2021",
    shift: "Cả ngày (7–19h)",
    workStatus: "active",
    locked: false,
    todayTasks: 4,
    completedTasks: 2,
    monthlyPerf: 88,
    rating: 4.7,
    specialty: "Ngoại khoa",
    room: "Phòng 3",
    licenseNo: "VN-VET-2017-0256",
    todayPatients: 2,
    notes: "Chuyên phẫu thuật triệt sản và chỉnh hình.",
  },
  {
    id: "NV-C04",
    name: "BS. Phạm Minh Đức",
    avatar: "PĐ",
    department: "clinic",
    position: "Bác sĩ da liễu",
    phone: "0904 444 555",
    email: "duc.pham@petcare.vn",
    joinDate: "01/04/2022",
    shift: "Sáng (7–13h)",
    workStatus: "on_leave",
    locked: false,
    todayTasks: 0,
    completedTasks: 0,
    monthlyPerf: 84,
    rating: 4.8,
    specialty: "Da liễu thú y",
    room: "Phòng 4",
    licenseNo: "VN-VET-2020-0134",
    todayPatients: 0,
    notes: "Nghỉ phép năm từ 19/05 đến 28/05/2026.",
  },
  {
    id: "NV-C05",
    name: "Trần Thị Bảo",
    avatar: "TB",
    department: "clinic",
    position: "Trợ lý thú y",
    phone: "0944 400 500",
    email: "bao.tran@petcare.vn",
    joinDate: "05/06/2022",
    shift: "Sáng (7–13h)",
    workStatus: "active",
    locked: false,
    todayTasks: 8,
    completedTasks: 5,
    monthlyPerf: 82,
    rating: 4.5,
    notes: "Hỗ trợ phòng khám, chuẩn bị dụng cụ và thuốc.",
  },
  {
    id: "NV-C06",
    name: "Nguyễn Thị Cúc",
    avatar: "NC",
    department: "clinic",
    position: "Trợ lý thú y",
    phone: "0915 515 515",
    email: "cuc.nguyen@petcare.vn",
    joinDate: "10/02/2026",
    shift: "Chiều (13–19h)",
    workStatus: "probation",
    locked: false,
    todayTasks: 5,
    completedTasks: 3,
    monthlyPerf: 74,
    rating: 4.2,
    notes: "Nhân viên thử việc. Đang học quy trình phòng khám.",
  },
  {
    id: "NV-G01",
    name: "Vũ Minh Tuấn",
    avatar: "VT",
    department: "grooming",
    position: "Groomer cao cấp",
    phone: "0911 100 200",
    email: "tuan.vu@petcare.vn",
    joinDate: "12/05/2020",
    shift: "Cả ngày (7–19h)",
    workStatus: "active",
    locked: false,
    todayTasks: 4,
    completedTasks: 3,
    monthlyPerf: 93,
    rating: 4.9,
    notes:
      "Chuyên cắt tỉa lông chó lớn và các giống đặc biệt. Đã đạt chứng chỉ iPET.",
  },
  {
    id: "NV-G02",
    name: "Hoàng Thị Mỹ",
    avatar: "HM",
    department: "grooming",
    position: "Groomer",
    phone: "0922 600 700",
    email: "my.hoang@petcare.vn",
    joinDate: "15/08/2023",
    shift: "Sáng (7–13h)",
    workStatus: "active",
    locked: false,
    todayTasks: 5,
    completedTasks: 3,
    monthlyPerf: 86,
    rating: 4.6,
    notes: "Giỏi grooming mèo và các giống nhỏ. Khách hàng rất hài lòng.",
  },
  {
    id: "NV-G03",
    name: "Lê Văn Nam",
    avatar: "LN",
    department: "grooming",
    position: "Groomer",
    phone: "0955 500 600",
    email: "nam.le@petcare.vn",
    joinDate: "14/10/2022",
    shift: "Chiều (13–19h)",
    workStatus: "on_leave",
    locked: false,
    todayTasks: 0,
    completedTasks: 0,
    monthlyPerf: 79,
    rating: 4.4,
    notes: "Đang nghỉ phép. Dự kiến quay lại làm từ 01/06/2026.",
  },
  {
    id: "NV-B01",
    name: "Đinh Thị Lan",
    avatar: "ĐL",
    department: "boarding",
    position: "Quản lý lưu trú",
    phone: "0922 200 300",
    email: "lan.dinh@petcare.vn",
    joinDate: "08/09/2021",
    shift: "Cả ngày (7–19h)",
    workStatus: "active",
    locked: false,
    todayTasks: 6,
    completedTasks: 4,
    monthlyPerf: 90,
    rating: 4.7,
    notes:
      "Quản lý toàn bộ khu vực lưu trú. Theo dõi sức khỏe thú cưng hàng ngày.",
  },
  {
    id: "NV-B02",
    name: "Phạm Văn Sơn",
    avatar: "PS",
    department: "boarding",
    position: "Nhân viên chăm sóc",
    phone: "0933 700 800",
    email: "son.pham@petcare.vn",
    joinDate: "20/03/2023",
    shift: "Sáng (7–13h)",
    workStatus: "active",
    locked: false,
    todayTasks: 7,
    completedTasks: 5,
    monthlyPerf: 83,
    rating: 4.5,
    notes: "Chăm sóc thú cưng lưu trú, dắt đi dạo và cho ăn đúng giờ.",
  },
  {
    id: "NV-B03",
    name: "Ngô Thị Hằng",
    avatar: "NH",
    department: "boarding",
    position: "Nhân viên chăm sóc",
    phone: "0944 800 900",
    email: "hang.ngo@petcare.vn",
    joinDate: "05/11/2023",
    shift: "Chiều (13–19h)",
    workStatus: "active",
    locked: false,
    todayTasks: 6,
    completedTasks: 4,
    monthlyPerf: 81,
    rating: 4.4,
    notes: "Ca chiều, dọn vệ sinh phòng và chăm sóc buổi tối.",
  },
  {
    id: "NV-R01",
    name: "Nguyễn Văn Hùng",
    avatar: "NH",
    department: "reception",
    position: "Trưởng lễ tân",
    phone: "0933 300 400",
    email: "hung.nguyen@petcare.vn",
    joinDate: "21/01/2022",
    shift: "Sáng (7–13h)",
    workStatus: "active",
    locked: false,
    todayTasks: 12,
    completedTasks: 8,
    monthlyPerf: 89,
    rating: 4.6,
    notes: "Quản lý đặt lịch, tiếp đón và điều phối lịch hẹn toàn trung tâm.",
  },
  {
    id: "NV-R02",
    name: "Bùi Thị Hoa",
    avatar: "BH",
    department: "reception",
    position: "Lễ tân",
    phone: "0966 900 100",
    email: "hoa.bui@petcare.vn",
    joinDate: "17/09/2024",
    shift: "Chiều (13–19h)",
    workStatus: "active",
    locked: false,
    todayTasks: 9,
    completedTasks: 6,
    monthlyPerf: 77,
    rating: 4.3,
    notes: "Ca chiều. Hỗ trợ xử lý thanh toán và tư vấn dịch vụ.",
  },
  {
    id: "NV-A01",
    name: "Phạm Thị Huyền",
    avatar: "PH",
    department: "admin",
    position: "Kế toán",
    phone: "0966 600 700",
    email: "huyen.pham@petcare.vn",
    joinDate: "28/03/2023",
    shift: "Sáng (7–13h)",
    workStatus: "active",
    locked: true,
    todayTasks: 4,
    completedTasks: 1,
    monthlyPerf: 70,
    rating: 3.8,
    notes:
      "Tài khoản tạm khoá — đang xác minh sự cố báo cáo tài chính tháng 4.",
  },
  {
    id: "NV-A02",
    name: "Lý Văn Minh",
    avatar: "LM",
    department: "admin",
    position: "Quản lý hành chính",
    phone: "0977 700 800",
    email: "minh.ly@petcare.vn",
    joinDate: "04/08/2021",
    shift: "Cả ngày (7–19h)",
    workStatus: "active",
    locked: false,
    todayTasks: 5,
    completedTasks: 3,
    monthlyPerf: 88,
    rating: 4.5,
    notes: "Quản lý hợp đồng, nhân sự và hành chính chung của trung tâm.",
  },
];

export const DEPT_CONFIG: Record<
  Exclude<Department, "all">,
  {
    label: string;
    icon: ElementType;
    color: string;
    bg: string;
    border: string;
  }
> = {
  clinic: {
    label: "Phòng khám",
    icon: Stethoscope,
    color: "text-cyan-600",
    bg: "bg-cyan-50",
    border: "border-cyan-200",
  },
  grooming: {
    label: "Grooming",
    icon: Scissors,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
    border: "border-emerald-200",
  },
  boarding: {
    label: "Lưu trú",
    icon: BedDouble,
    color: "text-amber-600",
    bg: "bg-amber-50",
    border: "border-amber-200",
  },
  reception: {
    label: "Lễ tân",
    icon: Users,
    color: "text-violet-600",
    bg: "bg-violet-50",
    border: "border-violet-200",
  },
  admin: {
    label: "Kế toán & Hành chính",
    icon: Briefcase,
    color: "text-slate-600",
    bg: "bg-slate-100",
    border: "border-slate-200",
  },
};

export const DEPT_ORDER: Exclude<Department, "all">[] = [
  "clinic",
  "grooming",
  "boarding",
  "reception",
  "admin",
];

export const STATUS_CONFIG: Record<
  WorkStatus,
  { label: string; dot: string; cls: string }
> = {
  active: {
    label: "Đang làm việc",
    dot: "bg-emerald-500",
    cls: "bg-emerald-50 text-emerald-700 ring-1 ring-inset ring-emerald-200",
  },
  on_leave: {
    label: "Nghỉ phép",
    dot: "bg-slate-400",
    cls: "bg-slate-100 text-slate-500 ring-1 ring-inset ring-slate-200",
  },
  probation: {
    label: "Thử việc",
    dot: "bg-amber-400 animate-pulse",
    cls: "bg-amber-50 text-amber-700 ring-1 ring-inset ring-amber-200",
  },
};

export const AVATAR_COLORS = [
  "from-cyan-400 to-cyan-600",
  "from-violet-400 to-violet-600",
  "from-emerald-400 to-emerald-600",
  "from-amber-400 to-amber-600",
  "from-rose-400 to-rose-600",
  "from-indigo-400 to-indigo-600",
  "from-slate-400 to-slate-600",
];

export const SHIFTS: Shift[] = [
  "Sáng (7–13h)",
  "Chiều (13–19h)",
  "Cả ngày (7–19h)",
];

export const WORK_STATUSES: { v: WorkStatus; label: string }[] = [
  { v: "active", label: "Đang làm việc" },
  { v: "on_leave", label: "Nghỉ phép" },
  { v: "probation", label: "Thử việc" },
];

export const EMPTY_STAFF: Omit<StaffMember, "id"> = {
  name: "",
  avatar: "",
  department: "clinic",
  position: "",
  phone: "",
  email: "",
  joinDate: "",
  shift: "Cả ngày (7–19h)",
  workStatus: "active",
  locked: false,
  todayTasks: 0,
  completedTasks: 0,
  monthlyPerf: 80,
  rating: 4.5,
  notes: "",
};
